services:
  - name: fastapi-app
    buildCommand: python3 -m pip install -r requirements.txt
    startCommand: uvicorn fastapi-deployment.main:app --host 0.0.0.0 --port $PORT
    github:
      branch: main
